<?php
   require("html_top.phtml");
?>
<form method="post">
<div>
         <label for="login">Login</label>
         <input type="text" name="login" id="login">
      </div>

      <div>
         <label for="heslo">Heslo</label>
         <input type="text" name="heslo" id="heslo">
      </div>

      <input type="submit" value="Uložit">

   </form>

<?php
    require("html_bottom.phtml");
?>