<!DOCTYPE html>
<html lang="cs">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link rel="stylesheet" href="style.css">
   <title>I2B aplikace</title>
</head>
<body>
<nav class="navigace">
      <ul>
         <li><a href="index.html">Úvod</a></li>
         <li><a href="kocky.php">Naše kočky</a></li>
         <li><a href="vlozeni.php">Přidat kočku</a></li>
         <li><a href="kontakt.html">Kontakt</a></li>
      </ul>
   </nav>
   <img class="logo" src="./images/logo.jpg" alt="logo" width="100" height="100">
   <h1>Mňauland</h1>
    <?php header('Clear-Site-Data: "cache", "cookies", "storage", "executionContexts"'); ?>