<?php
   require("html_top.phtml");
?>

<h2>Kočky k adopci</h2>
<?php foreach ($kocky as $kocka) { ?>
 <table>
   <tbody>
      <tr>
         <!--<td><img src="./custom/kockatest.jpg" width="300" height="175"></td>-->
         <td><img src="./custom/<?= $kocka["obrazek"] ?>" width="300" height="175"></td>
         <td>Jméno: <?= $kocka["jmeno"] ?></td>
         <td>Věk: <?= $kocka["vek"] ?></td>
         <td>Barva: <?= $kocka["barva"] ?></td>
         <td>Pohlaví: <?= $kocka["pohlavi"] ? "Samec" : "Samice"?></td> 
         <td>Očkování: <?= $kocka["ockovani"] ? "Ano" : "Ne"?></td>
         <td>Kastrace: <?= $kocka["kastrace"] ? "Ano" : "Ne"?></td>
         <td>Popisek: <?= $kocka["popisek"] ?></td>  
      </tr>
   </tbody>
</table>
<?php } ?>
<?php
   require("html_bottom.phtml");
?>